---
- :flist:
    - noitem
  :classname: Countdatetime
  :classname_downcase: countdatetime
  :items:
    - - countdatetime
      - datetime
      - 'false'
  :plural: countdatetimes
  :ar_version: 6.0
- :flist:
    - noitem
  :classname: Evnb
  :classname_downcase: evnb
  :items:
    - - time_id
      - integer
      - 'false'
    - - ennb_id
      - integer
      - 'false'
  :plural: evnbs
  :ar_version: 6.0
- :flist:
    - noitem
    - invalid
    - current
  :classname: Ennblist
  :classname_downcase: ennblist
  :items:
    - - stack
      - string
      - 'false'
    - - notebook
      - string
      - 'false'
    - - count
      - integer
      - 'false'
    - - tag_count
      - integer
      - 'false'
    - - start_datetime
      - datetime
      - 'false'
  :plural: ennblists
  :ar_version: 6.0
