#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

require 'arxutils'
require 'enop'
require 'simpleoptparse'

db_scheme_ary = [
  {
    :flist => %W!noitem!,
    :classname => "Countdatetime",
    :classname_downcase => "countdatetime",
    :items => [
              ["countdatetime" , "datetime", "false"],
            ],
    :plural => "countdatetimes"
  },

  {
    :flist => %W!noitem!,
    :classname => "Evnb",
    :classname_downcase => "evnb",
    :items => [
              ["time_id" , "integer", "false"],
              ["ennb_id" , "integer", "false"],
            ],
    :plural => "evnbs"
  },

  {
    :flist => %W!noitem invalid current!,
    :classname => "Ennblist",
    :classname_downcase => "ennblist",

    :items => [
              ["stack" , "string", "false"],
              ["notebook" , "string", "false"],
              ["count" , "integer", "false"],
              ["tag_count" , "integer", "false"],
              ["start_datetime" , "datetime", "false"],
             ],
    :plural => "ennblists"
  },
]

opts = { 
  db_dir: Arxutils::Dbutil::DB_DIR ,
  relation: {
    module: ["Enop" , "Dbutil"],
    filename: "dbrelation.rb",
    dir: "lib/enop/dbutil"
  }
}
banner = "Usage: bundle exec ruby exe/makemigrate [--makeconfig|--remigrate|--mysql|--sqlite3]"

Simpleoptparse::Simpleoptparse.parse( ARGV , opts , banner , Enop::VERSION , nil ){ |parser|
  parser.on('-c','--makeconfig'  ) { |x| opts["makeconfig"] = true }
  parser.on('-r','--remigrate'  ) { |x| opts["remigrate"] = true }
  parser.on('--mysql'  ) { |x| opts["dbconfig"] = Arxutils::Dbutil::DBCONFIG_MYSQL }
  parser.on('--sqlite3'  ) { |x| opts["dbconfig"] = Arxutils::Dbutil::DBCONFIG_SQLITE3 }
}
opts["makeconfig"] = !opts["makeconfig"].nil?
opts["remigrate"] = !opts["remigrate"].nil?

opts["dbconfig"] = Arxutils::Dbutil::DBCONFIG_SQLITE3 unless opts["dbconfig"]

env = ENV['ENV']
#env ||= "development"
env ||= "production"

Arxutils::Migrate.migrate(
                          Arxutils::Dbutil::DB_DIR,
                          Arxutils::Dbutil::CONFIG_DIR,
                          Arxutils::Dbutil::DATABASELOG,
                          Arxutils::Dbutil::MIGRATE_DIR,
                          env,
                          db_scheme_ary,
                          opts["dbconfig"],
                          opts,
                          )

