#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

require 'arxutils'
require 'enop'

data_ary = [
  {
    :flist => %W!noitem!,
    :classname => "Countdatetime",
    :classname_downcase => "countdatetime",
    :items => [
              ["countdatetime" , "datetime", "false"],
            ],
    :plural => "countdatetimes"
  },

  {
    :flist => %W!noitem!,
    :classname => "Evnb",
    :classname_downcase => "evnb",
    :items => [
              ["time_id" , "integer", "false"],
              ["ennb_id" , "integer", "false"],
            ],
    :plural => "evnbs"
  },

  {
    :flist => %W!base invalid current!,
    :classname => "Ennblist",
    :classname_downcase => "ennblist",

    :items => [
              ["stack" , "string", "false"],
              ["notebook" , "string", "false"],
              ["count" , "integer", "false"],
              ["tag_count" , "integer", "false"],
             ],
    :plural => "ennblists"
  },
]

dbconfig = Arxutils::Dbutil::DBCONFIG_MYSQL
dbconfig = Arxutils::Dbutil::DBCONFIG_SQLITE3

forced = true
Arxutils::Migrate.migrate(
                          data_ary,
                          0,
                          dbconfig,
                          forced
                          )

